### ISSUE TITLE
Can't add floor insulation in conditioned basement (fields ghosted)

### ISSUE THREAD

**Issue by joe-shade** [fishbaugher/WAweb-Issues#95]
We have had a few conditioned basements this year that extend under unconditioned porches, which would require us to insulate the floor joists between the conditioned basement and the unconditioned porch.  A current work around would be to list that portion of the basement as non-conditioned, or we could list a flat attic for that part of the basement.  Is the intent to model that situation as an attic, or was a conditioned basement extending under an unconditioned porch not considered?

**Comment by eckmanwe** [comment]
Correct, they are ghosted to be clear. Based upon our review, WAv8 ignored the Added Insulation for the floor assembly for Conditioned foundations. If you have examples from WAv8 where a single foundation entry covered the (2) conditions identified above (partially under conditioned space, partially under buffered or ambient space), AND insulation for the limited floor area was selected as an ECM, then please share them.

WAweb is clear in showing the user that floor insulation will not be considered, whereas previous versions would take the inputs and then ignore them anyway.

If you have examples from WAv8, then please share. Otherwise, there are (2) different floor conditions here, and they must be input separately for appropriate modeling to occur. Note: on the surface, unfinished attic does not seem appropriate, but it all comes down to what best matches the condition. Not getting a chance to vet this, I think a finished attic Outer Ceiling Joist (floored) looks alot like that condition (conditioned below, enclosed above, also separated by adjacent conditioned space by a wall). Regardless of the method,  mindful input is required to avoid double counting foundation walls, sill/rim loss, etc.

**Comment by joe-shade** [comment]
Thank you for the clear and quick response.  Part of my goal with these tickets is to determine if found issues are intended or not, AND have the answer documented for future review.  I will close this for now and request guidance from Commerce on how they would prefer us to treat these kinds of situations.
